app: ikmoons-cloud
stage: prod
component: http
name: ikmoons-cloud
inputs:
  src:
    hook: npm run build
    dist: ./
    exclude: # 被排除的文件或目录
      - .env
      - '.next/cache/**'
      - 'node_modules/**'
  serviceId: ${env:APIGW_CUSTOM_SERVICE} # api网关服务ID
  faas:
    runtime: Nodejs14.18
    framework: nextjs
    name: ${name}
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments:
      - key: STATIC_URL
        value: ${env:STATIC_URL}
    layers:
      - name: '${output:${stage}:${app}:${name}-layer.name}'
        version: '${output:${stage}:${app}:${name}-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release # 环境变量
    enableCORS: true # 允许跨域
    customDomains:
      - domain: ${env:APIGW_CUSTOM_DOMAIN}
        certId: ${env:APIGW_CUSTOM_DOMAIN_CERTID}
        pathMap: # 这里将 API 网关的 release 环境映射到根路径
          - path: /
            environment: release
        customMap: true
        isDefaultMapping: false
        protocols:
          - http
          - https
  region: ap-guangzhou
  isAutoCiDeploy: false
  assets: # 静态资源相关配置
    cos:
      bucket: ${env:BUCKET} # 这里创建的 COS 桶名称
      sources:
        - src: .next/static
          targetDir: /_next/static
        - src: public
          targetDir: /
      # acl:
      # permissions: public-read
    cdn:
      area: global
      domain: ${env:CDN_DOMAIN}
      autoRefresh: true
      refreshType: delete
      https:
        http2: on
        certId: ${env:CDN_DOMAIN_CERTID}
