# 当代码推动到 main 分支时，执行当前工作流程
# 更多配置信息: https://docs.github.com/cn/actions/getting-started-with-github-actions
name: deploy serverless scf
on: #监听的事件和分支配置
  push:
    branches:
      - main 
jobs:
  deploy:
    name: deploy serverless http
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install dependency
        run: npm install
      - name: build
        run: npm build
      - name: serverless scf deploy
        uses: woodyyan/tencent-serverless-action@main
        env: # 环境变量
          STAGE: dev #您的部署环境
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID，请在Settings-Secrets中配置
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key，请在Settings-Secrets中配置
          STATIC_URL: ${{ secrets.STATIC_URL }}
          APIGW_CUSTOM_DOMAIN: ${{ secrets.APIGW_CUSTOM_DOMAIN }}
          APIGW_CUSTOM_DOMAIN_CERTID: ${{ secrets.APIGW_CUSTOM_DOMAIN_CERTID }}
          APIGW_CUSTOM_SERVICE: ${{ secrets.APIGW_CUSTOM_SERVICE }}
          BUCKET: ${{ secrets.BUCKET }}
          CDN_DOMAIN: ${{ secrets.CDN_DOMAIN }}
          CDN_DOMAIN_CERTID: ${{ secrets.CDN_DOMAIN_CERTID }}
